"use server";

import {
  revalidatePath,
} from "next/cache";

import {
  redirect,
} from "next/navigation";

import {
  requireSocialProfile,
} from "@/lib/social/require-user";


function safePath(
  value:
    | FormDataEntryValue
    | null,
) {
  const path =
    String(
      value ?? "",
    );

  if (
    path.startsWith("/") &&
    !path.startsWith("//")
  ) {
    return path;
  }

  return "/social-connect";
}


/* ============================================================
   LIKE / UNLIKE

   Notification itself is generated by PostgreSQL V8 trigger.
   ============================================================ */

export async function toggleLike(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const postId =
    String(
      formData.get(
        "post_id",
      ) ?? "",
    );


  const returnTo =
    safePath(
      formData.get(
        "return_to",
      ),
    );


  if (!postId) {
    return;
  }


  const {
    data:
      existing,
  } =
    await supabase
      .from(
        "social_likes",
      )
      .select(
        "post_id",
      )
      .eq(
        "post_id",
        postId,
      )
      .eq(
        "user_id",
        user.id,
      )
      .maybeSingle();


  if (existing) {

    await supabase
      .from(
        "social_likes",
      )
      .delete()
      .eq(
        "post_id",
        postId,
      )
      .eq(
        "user_id",
        user.id,
      );


    /*
     * Remove the old like notification too.
     */
    await supabase
      .from(
        "social_notifications",
      )
      .delete()
      .eq(
        "actor_id",
        user.id,
      )
      .eq(
        "notification_type",
        "like",
      )
      .eq(
        "entity_id",
        postId,
      );

  } else {

    await supabase
      .from(
        "social_likes",
      )
      .insert({
        post_id:
          postId,

        user_id:
          user.id,
      });
  }


  revalidatePath(
    returnTo,
  );

  revalidatePath(
    "/social-connect",
  );
}



/* ============================================================
   SAVE / UNSAVE
   ============================================================ */

export async function toggleSave(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const postId =
    String(
      formData.get(
        "post_id",
      ) ?? "",
    );


  const returnTo =
    safePath(
      formData.get(
        "return_to",
      ),
    );


  if (!postId) {
    return;
  }


  const {
    data:
      existing,
  } =
    await supabase
      .from(
        "social_saved_posts",
      )
      .select(
        "post_id",
      )
      .eq(
        "user_id",
        user.id,
      )
      .eq(
        "post_id",
        postId,
      )
      .maybeSingle();


  if (existing) {

    await supabase
      .from(
        "social_saved_posts",
      )
      .delete()
      .eq(
        "user_id",
        user.id,
      )
      .eq(
        "post_id",
        postId,
      );

  } else {

    await supabase
      .from(
        "social_saved_posts",
      )
      .insert({
        user_id:
          user.id,

        post_id:
          postId,
      });
  }


  revalidatePath(
    returnTo,
  );

  revalidatePath(
    "/social-connect/saved",
  );
}



/* ============================================================
   COMMENT
   ============================================================ */

export async function addComment(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const postId =
    String(
      formData.get(
        "post_id",
      ) ?? "",
    );


  const body =
    String(
      formData.get(
        "body",
      ) ?? "",
    ).trim();


  const returnTo =
    safePath(
      formData.get(
        "return_to",
      ),
    );


  if (
    !postId ||
    body.length < 1 ||
    body.length > 1000
  ) {
    return;
  }


  const {
    error,
  } =
    await supabase
      .from(
        "social_comments",
      )
      .insert({
        post_id:
          postId,

        user_id:
          user.id,

        body,
      });


  /*
   * Comment + mention notifications
   * are generated by PostgreSQL triggers.
   */


  revalidatePath(
    returnTo,
  );

  revalidatePath(
    "/social-connect",
  );
}



/* ============================================================
   EDIT OWN COMMENT
   ============================================================ */

export async function editComment(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const commentId =
    String(
      formData.get(
        "comment_id",
      ) ?? "",
    );


  const body =
    String(
      formData.get(
        "body",
      ) ?? "",
    ).trim();


  const returnTo =
    safePath(
      formData.get(
        "return_to",
      ),
    );


  if (
    !commentId ||
    body.length < 1 ||
    body.length > 1000
  ) {
    return;
  }


  /*
   * ONLY comment author may edit.
   */
  await supabase
    .from(
      "social_comments",
    )
    .update({
      body,

      updated_at:
        new Date()
          .toISOString(),
    })
    .eq(
      "id",
      commentId,
    )
    .eq(
      "user_id",
      user.id,
    );


  revalidatePath(
    returnTo,
  );
}



/* ============================================================
   DELETE COMMENT

   Do NOT restrict to comment user here.

   RLS V9 decides whether current user is:
   - comment author
   - post owner
   - administrator/manager
   ============================================================ */

export async function deleteComment(
  formData: FormData,
) {
  const {
    supabase,
  } =
    await requireSocialProfile();


  const commentId =
    String(
      formData.get(
        "comment_id",
      ) ?? "",
    );


  const returnTo =
    safePath(
      formData.get(
        "return_to",
      ),
    );


  if (!commentId) {
    return;
  }


  await supabase
    .from(
      "social_comments",
    )
    .delete()
    .eq(
      "id",
      commentId,
    );


  revalidatePath(
    returnTo,
  );
}



/* ============================================================
   DELETE OWN POST
   ============================================================ */

export async function deletePost(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const postId =
    String(
      formData.get(
        "post_id",
      ) ?? "",
    );


  if (!postId) {
    return;
  }


  const {
    data: post,
  } =
    await supabase
      .from(
        "social_posts",
      )
      .select(
        "id, user_id, media_path",
      )
      .eq(
        "id",
        postId,
      )
      .eq(
        "user_id",
        user.id,
      )
      .maybeSingle();


  if (!post) {
    return;
  }


  const {
    error,
  } =
    await supabase
      .from(
        "social_posts",
      )
      .delete()
      .eq(
        "id",
        postId,
      )
      .eq(
        "user_id",
        user.id,
      );


  if (
    !error &&
    post.media_path
  ) {
    await supabase.storage
      .from(
        "social-media",
      )
      .remove([
        post.media_path,
      ]);
  }


  redirect(
    "/social-connect",
  );
}



/* ============================================================
   FOLLOW / UNFOLLOW

   Follow notification handled by V8 DB trigger.
   ============================================================ */

export async function toggleFollow(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const target =
    String(
      formData.get(
        "target_user_id",
      ) ?? "",
    );


  const username =
    String(
      formData.get(
        "username",
      ) ?? "",
    );


  if (
    !target ||
    target === user.id
  ) {
    return;
  }


  const {
    data:
      existing,
  } =
    await supabase
      .from(
        "social_follows",
      )
      .select(
        "follower_id",
      )
      .eq(
        "follower_id",
        user.id,
      )
      .eq(
        "following_id",
        target,
      )
      .maybeSingle();


  if (existing) {

    await supabase
      .from(
        "social_follows",
      )
      .delete()
      .eq(
        "follower_id",
        user.id,
      )
      .eq(
        "following_id",
        target,
      );


    await supabase
      .from(
        "social_notifications",
      )
      .delete()
      .eq(
        "actor_id",
        user.id,
      )
      .eq(
        "user_id",
        target,
      )
      .eq(
        "notification_type",
        "follow",
      );

  } else {

    await supabase
      .from(
        "social_follows",
      )
      .insert({
        follower_id:
          user.id,

        following_id:
          target,
      });
  }


  revalidatePath(
    `/social-connect/u/${username}`,
  );

  revalidatePath(
    "/social-connect",
  );
}



/* ============================================================
   NOTIFICATIONS
   ============================================================ */

export async function markNotificationRead(
  formData: FormData,
) {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  const id =
    String(
      formData.get(
        "id",
      ) ?? "",
    );


  if (!id) {
    return;
  }


  await supabase
    .from(
      "social_notifications",
    )
    .update({
      is_read:
        true,
    })
    .eq(
      "id",
      id,
    )
    .eq(
      "user_id",
      user.id,
    );


  revalidatePath(
    "/social-connect/notifications",
  );
}


export async function markAllNotificationsRead() {
  const {
    supabase,
    user,
  } =
    await requireSocialProfile();


  await supabase
    .from(
      "social_notifications",
    )
    .update({
      is_read:
        true,
    })
    .eq(
      "user_id",
      user.id,
    )
    .eq(
      "is_read",
      false,
    );


  revalidatePath(
    "/social-connect/notifications",
  );
}



/* ============================================================
   CHAT
   ============================================================ */

export async function startConversation(
  formData: FormData,
) {
  const {
    supabase,
  } =
    await requireSocialProfile();


  const targetUserId =
    String(
      formData.get(
        "target_user_id",
      ) ?? "",
    );


  if (!targetUserId) {
    return;
  }


  const {
    data:
      conversationId,

    error,
  } =
    await supabase.rpc(
      "social_get_or_create_conversation",
      {
        p_other_user:
          targetUserId,
      },
    );


  if (
    error ||
    !conversationId
  ) {
    redirect(
      `/social-connect/chats?error=${encodeURIComponent(
        error?.message ??
          "Unable to start conversation.",
      )}`,
    );
  }


  redirect(
    `/social-connect/chats/${conversationId}`,
  );
}



/* ============================================================
   LOGOUT
   ============================================================ */

export async function socialLogout() {
  const {
    supabase,
  } =
    await requireSocialProfile();


  await supabase.auth.signOut();


  redirect(
    "/social-connect",
  );
}
